apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cluster.local/nfs-subdir-external-provisioner
  creationTimestamp: "2026-03-23T08:20:45Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-3af789ea-0b01-4e4a-a9a7-f205d644bda1
  resourceVersion: "11341859"
  uid: 2bc00e73-ebd1-4e65-a514-66a32944aaa1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sample-domain1-pvc
    namespace: sample-domain1-ns
    resourceVersion: "11341855"
    uid: 3af789ea-0b01-4e4a-a9a7-f205d644bda1
  nfs:
    path: /data/k8s/sample-domain1-ns-sample-domain1-pvc-pvc-3af789ea-0b01-4e4a-a9a7-f205d644bda1
    server: 192.168.100.72
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2026-03-23T08:20:45Z"
  phase: Bound
